services:
  - type: web
    name: hostel-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE
        value: https://masoud-project-64gt.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
